---
- name: Destroy stage
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Destroy molecule instance(s)
      community.docker.docker_container:
        name: "{{ item.name }}"
        state: absent
      with_items: "{{ molecule_yml.platforms }}"
